export enum FETCH_BLOCKCHAIN {
  START = "FETCH_BLOCKCHAIN_START",
  SUCCESS = "FETCH_BLOCKCHAIN_SUCCESS",
  FAIL = "FETCH_BLOCKCHAIN_FAIL",
}

export enum ADD_NODE {
  START = "ADD_NODE_START",
  SUCCESS = "ADD_NODE_SUCCESS",
  FAIL = "ADD_NODE_FAIL",
}

export enum DELETE_NODE {
  START = "DELETE_NODE_START",
  SUCCESS = "DELETE_NODE_SUCCESS",
  FAIL = "DELETE_NODE_FAIL",
}

export enum MININIG_BLOCK {
  START = "MINING_BLOCK_START",
  SUCCESS = "MINING_BLOCK_SUCCESS",
  FAIL = "MINING_BLOCK_FAIL",
}

export enum TRANSFER_FUNDS {
  START = "TRANSFER_FUNDS_START",
  SUCCESS = "TRANSFER_FUNDS_SUCCESS",
  FAIL = "TRANSFER_FUNDS_FAIL",
}

export enum ERROR_BOX {
  CLOSE = "ERROR_BOX_CLOSE",
}
